name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if [ ! -d "upload_test" ]; then
            git clone git@github.com:michael-mvalue/upload_test.git
          fi
          cd upload_test
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          pkill uvicorn || true
          nohup uvicorn index:app --host 0.0.0.0 --port 8000 &